# Numpy

In [2]:
import numpy as np

In [5]:
obj = np.array([1, 2, 3])
print(obj)
print(type(obj))
print(obj.size)

[1 2 3]
<class 'numpy.ndarray'>
3


um array pode ser criado a partir de um objeto multidimensional

In [6]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
print(matriz.ndim)
print(matriz.shape)
print(matriz.size)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


O metodo arange cria um array com apenas uma dimensao(lista)

In [8]:
obj = np.arange(10)
print(obj)

[0 1 2 3 4 5 6 7 8 9]


Um array pode ter suas dimensoes modificadas
O metodo reshape recebe como parametro os tamanhos das dimensoes desejadas.

In [12]:
arange - np.arange(20)
print(obj.reshape(2, 3))

NameError: name 'arange' is not defined

Acessando as linhas do array

In [16]:
a = np.array([[10, 9, 8], [7, 6, 5]])
print(a[0, :])
print(a[1, :])
print(a[1, :2])

[10  9  8]
[7 6 5]
[7 6]


Operadores para arrays

In [18]:
M1 = np.array([[1, 2, 3], [4, 5, 6]])
M2 = np.array([[6, 5, 4], [3, 2, 1]])

print(M1 + M2)

[[7 7 7]
 [7 7 7]]
